import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/components/context/AppContext";
import { Providers as NextUiProviders } from "./providers";
import { geistMono, geistSans, poppins } from "@/lib/config/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.className} antialiased`}>
				<NextUiProviders>
					<AppProvider>{children}</AppProvider>
				</NextUiProviders>
			</body>
		</html>
	);
}
